"""Writes the evaluation report that the scenario-recovery claim rests on.

Kept as a written artefact under `deliverables/` rather than terminal output,
for the same reason `apps/eval` records its runs: a figure nobody can re-read
next month is a figure nobody can check.

The report states what was measured, what it means, and — at least as
importantly — what it does not mean. Two caveats are printed every time
because both are easy to forget and both change how the numbers should be
read: precision is bounded below by unplanted-but-genuine cells, and the
thresholds were not chosen blind.
"""

from __future__ import annotations

from pathlib import Path

from .analytics import TARGET_SCENARIOS, AnalyticsRun, leakage_statement
from .evaluation import ClassificationResult, RankingResult

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "deliverables" / "V050c-analytics-evaluation.md"


def write_report(
    run: AnalyticsRun,
    classifications: list[ClassificationResult],
    rankings: list[RankingResult],
) -> Path:
    lines: list[str] = []
    add = lines.append

    add("# V050c — Analytics evaluation against planted scenarios\n")
    add(
        "Generated by `npm run analytics:report`. Every figure below comes from running the "
        "five analysis SQL files against the generated dataset and scoring the results "
        "against scenario labels the analyses never received.\n"
    )

    add("## Leakage statement\n")
    add(f"{leakage_statement()}\n")

    add("## What each signal was scored against\n")
    add(
        "Each analysis is scored against the scenarios it is designed to detect, not against "
        "the union of all unmet-need labels. Scenario G is *defined* as need that produces "
        "almost no reports; marking the demand-driven analysis wrong for missing it would "
        "punish the design for working as intended. The ensemble row scores the combination, "
        "which is the claim that actually matters to a policymaker.\n"
    )
    add("| Signal | Target scenarios |")
    add("| --- | --- |")
    for key, scenarios in TARGET_SCENARIOS.items():
        add(f"| {key.replace('_', ' ')} | {', '.join(scenarios)} |")
    add("")

    add("## Classification results\n")
    add("| Signal | TP | FP | FN | Precision (95% CI) | Recall (95% CI) | F1 |")
    add("| --- | ---: | ---: | ---: | --- | --- | ---: |")
    for result in classifications:
        f1 = f"{result.f1:.2f}" if result.f1 is not None else "n/a"
        add(
            f"| {result.signal} | {result.true_positives} | {result.false_positives} | "
            f"{result.false_negatives} | {result.precision.render()} | "
            f"{result.recall.render()} | {f1} |"
        )
    add("")

    add("## Ranking results\n")
    add(
        "Recall@K is bounded by K divided by the number of relevant cells; the ceiling column "
        "shows what a perfect ranking could have reached at that K, because the raw figure "
        "alone reads as failure when it is arithmetic.\n"
    )
    add("| K | Hits | Recall@K | Ceiling | Precision@K | NDCG@K |")
    add("| ---: | ---: | ---: | ---: | ---: | ---: |")
    for result in rankings:
        recall = result.recall_at_k.value
        precision = result.precision_at_k.value
        add(
            f"| {result.k} | {result.hits_at_k} | "
            f"{recall:.1%} | {result.max_possible_recall:.1%} | "
            f"{precision:.1%} | {result.ndcg_at_k:.3f} |"
        )
    add("")

    add("## How to read these numbers\n")
    add(
        "**Precision is a lower bound, not an accuracy.** Only 162 of 2,508 district-sector "
        "cells carry a planted scenario. The other 2,346 are ordinary cells generated from "
        "real district characteristics with genuine variation, and some of them really do "
        "have high demand over a poor infrastructure indicator with no project. Those count "
        "as false positives here because they were not planted, even where flagging them was "
        "the right call. A perfect analysis would not score 100%.\n"
    )
    add(
        "**The thresholds were not chosen blind.** A sensitivity analysis over the demand and "
        "deficit thresholds was run against these labels before the values in "
        "`02_unmet_need.sql` were fixed. The primary justification is shortlist size — the top "
        "ventile of 2,508 cells is a list a ministry can work through, the top quartile is not "
        "— but a reader should treat these figures as optimistic relative to a genuinely "
        "held-out threshold choice.\n"
    )
    add(
        "**A wide interval is reported as unreportable rather than as a number.** Several "
        "signals have fewer than 25 planted examples, and a precision of '3 of 9' cannot "
        "distinguish a method that usually works from one that works half the time. This "
        "mirrors `MAX_INTERVAL_WIDTH_FOR_A_RATE` in `packages/domain/src/evaluation.ts`.\n"
    )

    add("## Known weaknesses\n")
    add(
        "Three signals are materially weaker than the rest, and tuning them further against "
        "these same labels would be fitting to the evaluation set rather than improving the "
        "method:\n"
    )
    add(
        "- **Execution / outcome gap** — only a handful of planted cells have enough reports "
        "on both sides of a completion date for a before/after comparison to mean anything. "
        "The method is sound; the sample is thin.\n"
        "- **Silent need** — the expected-reporting baseline is a mean within a deficit band, "
        "which is crude. This is the clearest candidate for a learned expected-reporting "
        "model, and the comparison against this baseline is what would justify adding one.\n"
        "- **Monitor existing project** — inherits the recall ceiling of the unmet-need step "
        "that feeds it, so it cannot exceed that step's coverage."
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    return OUTPUT
