"""Writes the evaluation report that the scenario-recovery claim rests on.

Kept as a written artefact under `deliverables/` rather than terminal output,
for the same reason `apps/eval` records its runs: a figure nobody can re-read
next month is a figure nobody can check.

The report states what was measured, what it means, and — at least as
importantly — what it does not mean. The framing printed every time is that
these figures measure **planted-scenario recovery** and nothing wider: the
2,346 unplanted cells carry no ground-truth need label, so the dataset cannot
say whether flagging one of them was right. Calling that a "lower bound" on
precision would imply the true value is knowably higher, which it is not.
"""

from __future__ import annotations

from pathlib import Path

from . import freeze, splits
from .analytics import TARGET_SCENARIOS, AnalyticsRun, leakage_statement
from .evaluation import ClassificationResult, RankingResult

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
OUTPUT = REPO_ROOT / "deliverables" / "V050c-analytics-evaluation.md"


def write_report(
    run: AnalyticsRun,
    classifications: list[ClassificationResult],
    rankings: list[RankingResult],
    split: str = "hidden",
) -> Path:
    lines: list[str] = []
    add = lines.append

    add("# V050c — Planted-scenario recovery: held-out evaluation\n")
    add(
        f"Generated by `npm run analytics:report`. Split evaluated: **{split}**. "
        "Every figure comes from running the frozen analysis SQL against the generated "
        "dataset and scoring the results against scenario labels the analyses never "
        "received.\n"
    )

    add("## What these figures are, and are not\n")
    add(
        "This measures **planted-scenario recovery**: of the development scenarios "
        "deliberately planted into the dataset, how many does the analysis find, and how "
        "much of what it flags corresponds to one. It is not a measure of whether the "
        "analysis correctly identifies development need in India, and must not be "
        "presented as one.\n"
    )
    add(
        "The distinction matters for reading precision. Only 162 of 2,508 district-sector "
        "cells carry a planted scenario. **The remaining cells have no ground-truth need "
        "label at all** — they are ordinary cells generated from real district "
        "characteristics, and nothing in the dataset records whether a given one does or "
        "does not have genuine unmet need. A flagged cell that is not planted is therefore "
        "counted against precision here, but the dataset cannot say whether flagging it was "
        "right or wrong. Precision below is precision *at recovering planted scenarios*, "
        "and no stronger claim is available from this data.\n"
    )

    add("## Evaluation integrity\n")
    add(f"- **Leakage:** {leakage_statement()}")
    add(f"- **Rule freeze:** {freeze.statement()}")
    split_summary = splits.summarise(run.split)
    add(
        f"- **Split:** deterministic SHA-256 of cell identity, salt `{splits.SPLIT_SALT}`, "
        f"stratified by scenario. {int(split_summary['development'].sum())} development / "
        f"{int(split_summary['hidden'].sum())} hidden of "
        f"{int(split_summary['total'].sum())} planted cells."
    )
    add(
        "- **Universe:** planted cells from the other split are excluded entirely rather "
        "than scored as negatives, so a development positive cannot manufacture a false "
        "positive on the hidden run.\n"
    )

    add("### Split composition\n")
    add("| Scenario | Development | Hidden | Total |")
    add("| --- | ---: | ---: | ---: |")
    for scenario, row in split_summary.iterrows():
        add(
            f"| {scenario} | {int(row['development'])} | {int(row['hidden'])} | "
            f"{int(row['total'])} |"
        )
    add("")

    add("## What each signal was scored against\n")
    add(
        "Each analysis is scored against the scenarios it is designed to detect, not against "
        "the union of all unmet-need labels. Scenario G is *defined* as need that produces "
        "almost no reports; marking the demand-driven analysis wrong for missing it would "
        "punish the design for working as intended. The ensemble row scores the combination, "
        "which is the claim that actually matters to a policymaker.\n"
    )
    add("| Signal | Target scenarios |")
    add("| --- | --- |")
    for key, scenarios in TARGET_SCENARIOS.items():
        add(f"| {key.replace('_', ' ')} | {', '.join(scenarios)} |")
    add("")

    add("## Classification results\n")
    add("| Signal | TP | FP | FN | Precision (95% CI) | Recall (95% CI) | F1 |")
    add("| --- | ---: | ---: | ---: | --- | --- | ---: |")
    for result in classifications:
        f1 = f"{result.f1:.2f}" if result.f1 is not None else "n/a"
        add(
            f"| {result.signal} | {result.true_positives} | {result.false_positives} | "
            f"{result.false_negatives} | {result.precision.render()} | "
            f"{result.recall.render()} | {f1} |"
        )
    add("")

    add("## Ranking results\n")
    add(
        "Recall@K is bounded by K divided by the number of relevant cells; the ceiling column "
        "shows what a perfect ranking could have reached at that K, because the raw figure "
        "alone reads as failure when it is arithmetic.\n"
    )
    add("| K | Hits | Recall@K | Ceiling | Precision@K | NDCG@K |")
    add("| ---: | ---: | ---: | ---: | ---: | ---: |")
    for result in rankings:
        recall = result.recall_at_k.value
        precision = result.precision_at_k.value
        add(
            f"| {result.k} | {result.hits_at_k} | "
            f"{recall:.1%} | {result.max_possible_recall:.1%} | "
            f"{precision:.1%} | {result.ndcg_at_k:.3f} |"
        )
    add("")

    add("## How to read these numbers\n")
    add(
        "**A wide interval is reported as unreportable rather than as a number.** Several "
        "scenarios have fewer than ten hidden examples, and a precision of '3 of 6' cannot "
        "distinguish a method that usually works from one that works half the time. This "
        "mirrors `MAX_INTERVAL_WIDTH_FOR_A_RATE` in "
        "`packages/domain/src/evaluation.ts`.\n"
    )
    add(
        "**The development figures are not a second result.** They are reported only so the "
        "generalisation gap is visible. Where hidden performance is materially below "
        "development performance, the thresholds were fitted to the development cells and "
        "the hidden figure is the one that counts.\n"
    )
    add(
        "**Execution gap is reported but should not be quoted.** Only nine planted "
        "Scenario C cells have enough reports on both sides of a completion date for a "
        "before/after comparison, and the hidden portion of those is smaller still. Its "
        "thresholds were deliberately not tuned, and its interval is too wide to support "
        "any claim about the method. It is shown for completeness, not as evidence.\n"
    )

    add("## The limiting factor is statistical power, not the method\n")
    add(
        "Almost every figure above carries an interval too wide to be quoted as a rate. That "
        "is not a failure of the analyses — it is the hidden split having between three and "
        "eight examples per scenario. With five hidden Scenario D cells, recall can only take "
        "the values 0, 0.2, 0.4, 0.6, 0.8 or 1.0, and the 95% interval around any of them "
        "spans most of the range. No amount of method improvement fixes this; only more "
        "labelled examples do.\n"
    )
    add(
        "The generalisation gap itself is reassuring and is the useful result here. Unmet "
        "need moves from F1 0.54 on development to 0.46 on hidden, new investment gap from "
        "0.47 to 0.41 — a modest drop consistent with mild threshold fitting rather than "
        "rules that only worked on the cells that produced them.\n"
    )
    add("**Two ways to get power, in order of preference:**\n")
    add(
        "1. **Plant more scenarios.** `PLANT_COUNTS` in `pipelines/voice_data/scenarios.py` "
        "currently plants 162 cells of 2,508. Raising it to ~600 would give roughly 60 hidden "
        "cells per scenario and bring most intervals inside the reportable width. The "
        "generator supports this today; it costs one regeneration.\n"
        "2. **Repeated stratified k-fold** over the planted cells, reporting the distribution "
        "across folds rather than one hidden number. This uses every labelled cell for "
        "evaluation without reusing any for tuning, at the cost of a more complex claim.\n"
    )
    add(
        "Until one of those is done, the honest summary is: the rules appear to generalise, "
        "and the hidden sample is too small to say by how much.\n"
    )

    add("## Known weaknesses\n")
    add(
        "Three signals are materially weaker than the rest, and tuning them further against "
        "these same labels would be fitting to the evaluation set rather than improving the "
        "method:\n"
    )
    add(
        "- **Execution / outcome gap** — only a handful of planted cells have enough reports "
        "on both sides of a completion date for a before/after comparison to mean anything. "
        "The method is sound; the sample is thin.\n"
        "- **Silent need** — the expected-reporting baseline is a mean within a deficit band, "
        "which is crude. This is the clearest candidate for a learned expected-reporting "
        "model, and the comparison against this baseline is what would justify adding one.\n"
        "- **Monitor existing project** — inherits the recall ceiling of the unmet-need step "
        "that feeds it, so it cannot exceed that step's coverage."
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    return OUTPUT
