"""Table shapes, and the column exclusions that keep evaluation labels out.

Loading happens in two steps on purpose.

1. Parquet and CSV land in `_staging_*` tables with autodetected schemas.
   Parquet already carries its types, so nothing is guessed from text.
2. Each final table is built from staging with an explicit
   `CREATE OR REPLACE TABLE ... PARTITION BY ... CLUSTER BY ... AS SELECT`.

Step 2 is where three things happen that a plain load cannot do: partitioning
and clustering are declared, `GEOGRAPHY` is constructed from the latitude and
longitude columns, and — most importantly — evaluation labels are dropped by
name.

`SELECT * EXCEPT (...)` is used for the exclusion rather than an explicit
column list. An explicit list silently drops any column added upstream later;
`EXCEPT` silently *keeps* it. Neither failure is free, so the choice is backed
by `validate.py`, which refuses any column in the analytics dataset whose name
matches a forbidden pattern. The exclusion states intent; the validator
enforces it.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# ── What must never reach the analytics dataset ────────────────────────────

#: Dropped from `district_sector_month`.
MASTER_LABELS = (
    "scenario_id",
    "ground_truth_scenario",
    "expected_interpretation",
    "ground_truth_unmet_need",
    "ground_truth_investment_gap",
    "ground_truth_execution_gap",
    "ground_truth_emerging_hotspot",
    "ground_truth_silent_need",
)

#: Dropped from `canonical_issues`. `severity_ground_truth` and the three
#: `true_*` columns are the generator's private truth about an issue; the
#: product never observes them.
ISSUE_LABELS = (
    "severity_ground_truth",
    "true_status",
    "true_project_overlap",
    "true_infrastructure_deficit",
    "scenario_id",
)

#: Dropped from `citizen_reports`. `canonical_issue_id` deliberately stays:
#: it is the operational grouping key the product genuinely assigns, not a
#: planted label. It is withheld only by the deduplication evaluation itself.
REPORT_LABELS = ("scenario_id",)

#: Any analytics column whose lowercased name contains one of these is a leak.
#: Checked by `validate.py` against the live dataset, so a future upstream
#: column called `ground_truth_something` fails the build rather than quietly
#: training a model.
FORBIDDEN_SUBSTRINGS = ("ground_truth", "scenario_", "_truth", "planted")

#: Exempted from the substring rule because they are legitimately named and
#: carry no label. Kept short and reviewed.
FORBIDDEN_EXEMPTIONS = frozenset()


@dataclass(frozen=True)
class TableSpec:
    """One analytical table: how it is built, partitioned and clustered."""

    name: str
    staging: str
    select: str
    partition_by: str | None = None
    cluster_by: tuple[str, ...] = ()
    description: str = ""
    require_partition_filter: bool = False

    def create_sql(self, dataset: str) -> str:
        parts = [f"CREATE OR REPLACE TABLE `{dataset}.{self.name}`"]
        if self.partition_by:
            parts.append(f"PARTITION BY {self.partition_by}")
        if self.cluster_by:
            parts.append(f"CLUSTER BY {', '.join(self.cluster_by)}")
        options = [f'description="""{self.description.strip()}"""']
        if self.require_partition_filter:
            options.append("require_partition_filter=TRUE")
        parts.append(f"OPTIONS({', '.join(options)})")
        parts.append("AS")
        parts.append(self.select.format(staging=f"`{dataset}.{self.staging}`"))
        return "\n".join(parts)


# ── Analytics dataset ──────────────────────────────────────────────────────

ANALYTICS_TABLES: tuple[TableSpec, ...] = (
    TableSpec(
        name="citizen_reports",
        staging="_staging_citizen_reports",
        # Partitioned by report date: every analysis is time-windowed, and this
        # is the only table where partition pruning changes the bill.
        partition_by="DATE(created_at)",
        cluster_by=("state_code", "district_key", "sector"),
        description=(
            "Citizen reports. SYNTHETIC: generated by pipelines/voice_data, conditioned on real "
            "Census 2011 characteristics. Not real complaints. "
            "`location` is derived — a point inside the district's state, not a surveyed position; "
            "district-level aggregation is sound, sub-district distance analysis is not."
        ),
        select="""
SELECT
  * EXCEPT ({excluded}),
  -- Built here rather than stored upstream so the warehouse owns one
  -- canonical spatial representation. Longitude first: ST_GEOGPOINT takes
  -- (longitude, latitude) and the reversed argument order is the classic
  -- way to put every report in the wrong hemisphere.
  ST_GEOGPOINT(longitude, latitude) AS location
FROM {staging}
""".replace("{excluded}", ", ".join(REPORT_LABELS)),
    ),
    TableSpec(
        name="canonical_issues",
        staging="_staging_canonical_issues",
        partition_by="DATE(first_seen_at)",
        cluster_by=("district_key", "sector"),
        description=(
            "Canonical issues: the distinct real-world problems reports observe. SYNTHETIC. "
            "Generator ground truth (severity_ground_truth, true_*) is held back in voice_eval."
        ),
        select="""
SELECT
  * EXCEPT ({excluded}),
  ST_GEOGPOINT(lon, lat) AS location
FROM {staging}
""".replace("{excluded}", ", ".join(ISSUE_LABELS)),
    ),
    TableSpec(
        name="district_sector_month",
        staging="_staging_district_sector_month",
        # Monthly partitions over a 24-month window: 24 partitions, which is
        # about pruning trend windows rather than about size.
        partition_by="month_start",
        cluster_by=("state_code", "district_key", "sector"),
        description=(
            "The analytical grain: district x sector x month. Mixed provenance — demographics "
            "are real Census 2011, infrastructure is real where a district table existed and "
            "derived elsewhere (see infrastructure_data_origin), citizen signal and investment "
            "are synthetic. Evaluation labels are held back in voice_eval."
        ),
        select="""
SELECT
  * EXCEPT ({excluded}),
  DATE(year, month, 1) AS month_start
FROM {staging}
""".replace("{excluded}", ", ".join(MASTER_LABELS)),
    ),
    TableSpec(
        name="public_projects",
        staging="_staging_public_projects",
        # The SELECT below materialises `sanction_date` as a DATE. BigQuery
        # accepts a DATE column directly as a partition expression; wrapping
        # that output alias in DATE(...) is not a supported CTAS partition
        # expression and makes the first real deployment fail after staging.
        partition_by="sanction_date",
        cluster_by=("district_key", "sector", "project_status"),
        description=(
            "SYNTHETIC project records. Scheme names are real central programmes; every "
            "sanction, release, expenditure and date attached to them is generated. "
            "No row is evidence about any real programme's disbursement or delivery."
        ),
        select="""
SELECT
  * EXCEPT (sanction_date, start_date, expected_completion_date, actual_completion_date),
  -- CSV dates arrive as strings; SAFE.PARSE_DATE keeps a malformed value as
  -- NULL rather than failing the whole load.
  SAFE.PARSE_DATE('%Y-%m-%d', sanction_date) AS sanction_date,
  SAFE.PARSE_DATE('%Y-%m-%d', start_date) AS start_date,
  SAFE.PARSE_DATE('%Y-%m-%d', expected_completion_date) AS expected_completion_date,
  SAFE.PARSE_DATE('%Y-%m-%d', actual_completion_date) AS actual_completion_date
FROM {staging}
""",
    ),
    TableSpec(
        name="district_demographics",
        staging="_staging_district_demographics",
        # 627 rows. Deliberately unpartitioned: partition metadata would cost
        # more than it could ever save.
        cluster_by=("state_code",),
        description=(
            "REAL. Census of India 2011 Primary Census Abstract, retrieved from data.gov.in "
            "under the Government Open Data License - India. population_density is the one "
            "derived column (equal-area assumption); see population_density_origin."
        ),
        select="SELECT * FROM {staging}",
    ),
    TableSpec(
        name="district_infrastructure",
        staging="_staging_district_infrastructure",
        cluster_by=("state_code", "sector"),
        description=(
            "MIXED provenance, per row. data_origin='real' where a published district table "
            "covered that district-sector (151 of 2,508 cells); 'derived' elsewhere, modelled "
            "from Census characteristics. A derived value is a modelling input, never a "
            "statistic about that district."
        ),
        select="SELECT * FROM {staging}",
    ),
    TableSpec(
        name="district_master",
        staging="_staging_district_master",
        cluster_by=("state_code",),
        description=(
            "Real Census 2011 district and state codes. Coordinates are DERIVED — a "
            "deterministic point inside the state, not a centroid."
        ),
        select="""
SELECT
  *,
  ST_GEOGPOINT(longitude, latitude) AS location
FROM {staging}
""",
    ),
)


# ── Evaluation dataset ─────────────────────────────────────────────────────

EVAL_TABLES: tuple[TableSpec, ...] = (
    TableSpec(
        name="planted_scenarios",
        staging="_staging_planted_scenarios",
        cluster_by=("district_key", "sector"),
        description=(
            "EVALUATION LABELS. The planted scenario inventory. Never readable by analytics, "
            "ML features, or Gemini. A synthetic scenario says nothing about the real district "
            "it was assigned to."
        ),
        select="SELECT * FROM {staging}",
    ),
    TableSpec(
        name="district_sector_month_labels",
        staging="_staging_district_sector_month",
        cluster_by=("district_key", "sector"),
        description=(
            "EVALUATION LABELS only: the ground-truth columns stripped from the analytics "
            "copy of district_sector_month, keyed so they can be joined at scoring time."
        ),
        select="""
SELECT
  district_key,
  state_code,
  district_code,
  sector,
  year,
  month,
  {labels}
FROM {staging}
""".replace("{labels}", ",\n  ".join(MASTER_LABELS)),
    ),
    TableSpec(
        name="canonical_issue_labels",
        staging="_staging_canonical_issues",
        cluster_by=("district_key", "sector"),
        description="EVALUATION LABELS only: the generator's private truth about each issue.",
        select="""
SELECT
  canonical_issue_id,
  district_key,
  sector,
  {labels}
FROM {staging}
""".replace("{labels}", ",\n  ".join(ISSUE_LABELS)),
    ),
)


def staging_tables() -> tuple[str, ...]:
    """Every staging table, so the loader can clean them up after building."""
    return tuple(
        dict.fromkeys(spec.staging for spec in (*ANALYTICS_TABLES, *EVAL_TABLES))
    )
