"""Step 6 — the descriptive statistics that let a reader judge the dataset.

Written to `data/metadata/summary.md` as well as printed, so the shape of a
generated run is recorded beside the data rather than living in a terminal
scrollback.
"""

from __future__ import annotations

import pandas as pd
import pyarrow.parquet as pq

from . import config
from .scenarios import SCENARIOS

#: Identifiers keep their leading zeros; see the note in validate.py.
_CODES = {"state_code": str, "district_code": str, "district_key": str}


def _fmt(value) -> str:
    return f"{value:,}" if isinstance(value, (int,)) else str(value)


def run() -> str:
    reports_path = config.SYNTHETIC / "citizen_reports.parquet"
    if not reports_path.exists():
        raise SystemExit("Nothing to summarise; run `npm run data:generate` first.")

    reports = pq.read_table(
        reports_path,
        columns=[
            "report_id", "state_code", "district_key", "sector", "language",
            "input_channel", "input_mode", "created_at", "severity",
            "canonical_issue_id", "citizen_id_hash", "data_origin",
        ],
    ).to_pandas()
    issues = pd.read_csv(config.SYNTHETIC / "canonical_issues.csv", low_memory=False, dtype=_CODES)
    master_districts = pd.read_csv(config.MASTER / "district_master.csv", dtype=_CODES)
    demographics = pd.read_csv(config.PROCESSED / "demographics.csv", dtype=_CODES)
    investments = pd.read_csv(config.PROCESSED / "public_investments.csv", low_memory=False, dtype=_CODES)
    planted = pd.read_csv(config.SYNTHETIC / "planted_scenarios.csv", dtype=_CODES)
    dsm = pq.read_table(config.MASTER / "district_sector_master.parquet").to_pandas()
    sources = pd.read_csv(config.METADATA / "sources.csv")

    created = pd.to_datetime(reports["created_at"])
    monthly = created.dt.to_period("M").value_counts().sort_index()

    disk_bytes = sum(
        path.stat().st_size
        for folder in (config.PROCESSED, config.SYNTHETIC, config.MASTER, config.METADATA)
        for path in folder.glob("*")
        if path.is_file()
    )

    lines: list[str] = []
    add = lines.append

    add("# VOICE dataset summary\n")
    add("Generated by `pipelines/voice_data`. Regenerate with the commands in `docs/data/README.md`.\n")

    add("## Overview\n")
    add(f"- **States/UTs:** {master_districts['state_code'].nunique()}")
    add(f"- **Districts:** {len(master_districts):,}")
    add(f"- **Citizen reports:** {len(reports):,}")
    add(f"- **Canonical issues:** {len(issues):,}")
    add(f"- **Unique citizens:** {reports['citizen_id_hash'].nunique():,}")
    add(f"- **Projects:** {len(investments):,}")
    add(f"- **Languages:** {reports['language'].nunique()}")
    add(f"- **Time range:** {created.min():%Y-%m-%d} to {created.max():%Y-%m-%d} ({config.MONTHS} months)")
    add(f"- **Master rows:** {len(dsm):,} (district × sector × month)")
    add(f"- **Disk size (processed + synthetic + master + metadata):** {disk_bytes / 1_048_576:.1f} MB\n")

    add("## Provenance\n")
    add(f"- Sources retrieved successfully: {(sources['retrieval_status'] == 'ok').sum()}")
    add(f"- Sources investigated but not ingested: {(sources['retrieval_status'] == 'not_attempted').sum()}")
    add(f"- Demographic rows (real, Census 2011): {len(demographics):,}")
    real_cells = 0
    for sector in config.SECTORS:
        table = pd.read_csv(
            config.PROCESSED / f"{ {'roads': 'road'}.get(sector, sector) }_infrastructure.csv"
        )
        real_cells += int((table["data_origin"] == "real").sum())
    total_cells = len(demographics) * len(config.SECTORS)
    add(
        f"- Infrastructure cells anchored on real district tables: {real_cells:,} of {total_cells:,} "
        f"({100 * real_cells / total_cells:.1f}%); the remainder are marked `derived`"
    )
    add(f"- Citizen reports, canonical issues and projects: 100% `synthetic`\n")

    add("## Sector distribution\n")
    add("| Sector | Reports | Share | Canonical issues |")
    add("| --- | ---: | ---: | ---: |")
    for sector, count in reports["sector"].value_counts().items():
        share = 100 * count / len(reports)
        add(f"| {sector} | {count:,} | {share:.1f}% | {int((issues['sector'] == sector).sum()):,} |")
    add("")

    add("## Languages\n")
    add("| Language | Reports | Share |")
    add("| --- | ---: | ---: |")
    for language, count in reports["language"].value_counts().items():
        add(f"| {language} | {count:,} | {100 * count / len(reports):.1f}% |")
    add("")

    add("## Channels and input modes\n")
    add("| Channel | Share | | Mode | Share |")
    add("| --- | ---: | --- | --- | ---: |")
    channels = reports["input_channel"].value_counts(normalize=True)
    modes = reports["input_mode"].value_counts(normalize=True)
    for i in range(max(len(channels), len(modes))):
        left = f"| {channels.index[i]} | {100 * channels.iloc[i]:.1f}% " if i < len(channels) else "| | "
        right = f"| | {modes.index[i]} | {100 * modes.iloc[i]:.1f}% |" if i < len(modes) else "| | | |"
        add(left + right)
    add("")

    add("## Monthly distribution\n")
    add("| Month | Reports |")
    add("| --- | ---: |")
    for period, count in monthly.items():
        add(f"| {period} | {count:,} |")
    add("")

    add("## Planted scenarios\n")
    add("| Code | Scenario | Expected interpretation | Cells | Reports |")
    add("| --- | --- | --- | ---: | ---: |")
    reports_by_scenario = (
        dsm.groupby("ground_truth_scenario")["citizen_report_count"].sum().to_dict()
    )
    for code, scenario in SCENARIOS.items():
        cells = int((planted["scenario_code"] == code).sum())
        add(
            f"| {code} | {scenario.name} | {scenario.expected_interpretation} | "
            f"{cells} | {int(reports_by_scenario.get(code, 0)):,} |"
        )
    unplanted = int((dsm["ground_truth_scenario"] == "none").sum())
    add(
        f"| none | (unplanted, ordinary cells) | — | {unplanted // config.MONTHS} | "
        f"{int(reports_by_scenario.get('none', 0)):,} |"
    )
    add("")

    add("## Top states by report volume\n")
    add("| State | Reports | Districts |")
    add("| --- | ---: | ---: |")
    by_state = reports["state_code"].value_counts().head(10)
    state_names = master_districts.drop_duplicates("state_code").set_index("state_code")["state_name"]
    for state_code, count in by_state.items():
        districts = int((master_districts["state_code"] == state_code).sum())
        add(f"| {state_names.get(state_code, state_code)} | {count:,} | {districts} |")
    add("")

    add("## Duplicate structure\n")
    per_issue = reports.groupby("canonical_issue_id").size()
    add(f"- Reports per canonical issue: mean {per_issue.mean():.2f}, median {per_issue.median():.0f}, max {per_issue.max():,}")
    add(f"- Issues observed by a single report: {int((per_issue == 1).sum()):,} ({100 * (per_issue == 1).mean():.1f}%)")
    per_citizen = reports.groupby("citizen_id_hash").size()
    add(f"- Reports per citizen: mean {per_citizen.mean():.2f}, max {per_citizen.max():,}\n")

    text = "\n".join(lines)
    (config.METADATA / "summary.md").write_text(text, encoding="utf-8")
    return text
